### ISSUE TITLE
此导航站主题懒人建站模板

### ISSUE THREAD

**Issue by cyolc932** [shenweiyan/WebStack-Hugo#11]
https://github.com/Hugo-Template/WebStack-Hugo-Template

**Comment by shenweiyan** [comment]
又学习到一种新的 Hugo 自动发布技能，涨知识了 >.<

之前一直用类似于 [这样](https://github.com/shenweiyan/WebSiteSRC/blob/main/.github/workflows/HugoAction.yml) 的 HugoActions 来自动发布 Hugo 站点，包括 [https://nav.bioitee.com/](https://nav.bioitee.com/) 和 [https://www.shumlab.com/](https://www.shumlab.com/)。

**Comment by cyolc932** [comment]
> 又学习到一种新的 Hugo 自动发布技能，涨知识了 >.<
> 
> 之前一直用类似于 [这样](https://github.com/shenweiyan/WebSiteSRC/blob/main/.github/workflows/HugoAction.yml) 的 HugoActions 来自动发布 Hugo 站点，包括 https://nav.bioitee.com/ 和 https://www.shumlab.com/。

这个action需要多少个🔑

**Comment by shenweiyan** [comment]
> > 又学习到一种新的 Hugo 自动发布技能，涨知识了 >.<
> > 之前一直用类似于 [这样](https://github.com/shenweiyan/WebSiteSRC/blob/main/.github/workflows/HugoAction.yml) 的 HugoActions 来自动发布 Hugo 站点，包括 https://nav.bioitee.com/ 和 [https://www.shumlab.com/。](https://www.shumlab.com/%E3%80%82)
> 
> 这个action需要多少个🔑

只需要一个 `PERSONAL_ACCESS_TOKEN` 就可以了，指定 branch 后，只要该 branch 有变动（push），就会触发自动化构建部署。

**Comment by cyolc932** [comment]
> > > 又学习到一种新的 Hugo 自动发布技能，涨知识了 >.<
> > > 之前一直用类似于 [这样](https://github.com/shenweiyan/WebSiteSRC/blob/main/.github/workflows/HugoAction.yml) 的 HugoActions 来自动发布 Hugo 站点，包括 https://nav.bioitee.com/ 和 [https://www.shumlab.com/。](https://www.shumlab.com/%E3%80%82)
> > 
> > 
> > 这个action需要多少个🔑
> 
> 只需要一个 `PERSONAL_ACCESS_TOKEN` 就可以了，指定 branch 后，只要该 branch 有变动（push），就会触发自动化构建部署。

可以弄个github组织来专门独立放开发的作品，听说github组织额度和个人账号额度是独立计算，不过组织密钥令牌我也不知道怎么申请
