### ISSUE TITLE
如何实现搜索栏跟随“夜间模式”变化？

### ISSUE THREAD

**Issue by JeamUmika** [shenweiyan/WebStack-Hugo#12]
![图片](https://user-images.githubusercontent.com/93057377/220707791-04fdc6c9-ac79-4b32-8774-b3a9371efaab.png)

![图片](https://user-images.githubusercontent.com/93057377/220693330-42142431-e6ad-41cb-82e2-27122841f038.png)

**Comment by shenweiyan** [comment]
不是很懂你说的搜索栏跟随“夜间模式”变化指的是什么

**Comment by JeamUmika** [comment]
> 不是很懂你说的搜索栏跟随“夜间模式”变化指的是什么

上面的两张照片，一张是“日间模式”下的白色，一张是“夜间模式”的黑色。点按右下角按钮切换到“夜间模式“时搜索栏变成黑色。
![Screenshot_20230223-105007_Chrome.png](https://user-images.githubusercontent.com/93057377/220811159-3f624504-79fd-4084-8ab1-443b5eee7379.png)

**Comment by shenweiyan** [comment]
你是想把搜索那里的背景图去掉，然后实现搜索栏跟随“夜间模式”变化成黑色？

如果是这样的话，你在 `layouts/partials/footer.html` 文件中把包含 `$("#search-bg").css("background-image" ...,` 的 3 行都注释掉就可以了：
![image](https://user-images.githubusercontent.com/26101369/220813780-fb568227-17d0-4bb4-a145-af38f959ca86.png)

**Comment by JeamUmika** [comment]
> 你是想把搜索那里的背景图去掉，然后实现搜索栏跟随“夜间模式”变化成黑色？
> 
> 如果是这样的话，你有 2 种方法可以实现：
> 
>     1. 在 `config.toml` 中把 `searchImageL` 和 `searchImageD` 都设置为空；
> 
>     2. 在 `layouts/partials/footer.html` 文件中把包含 `$("#search-bg").css("background-image" ...,` 的 3 行都注释掉就可以了：
>        ![image](https://user-images.githubusercontent.com/26101369/220813780-fb568227-17d0-4bb4-a145-af38f959ca86.png)

这两个步骤似乎只是去掉了背景图，搜索栏在“日间模式”下没有达到上面所述的效果（“夜间模式”达到了）

![图片](https://user-images.githubusercontent.com/93057377/220815906-0a214b66-d9dc-4f72-a087-82e9f72c0c13.png)

**Comment by shenweiyan** [comment]
那你把 `.header-big #search-text` 的 `background-color` 属性去掉就可以了~
![image](https://user-images.githubusercontent.com/26101369/220817082-a7f32e98-62bc-4777-8ce0-30daee3d478b.png)

**Comment by JeamUmika** [comment]
> 那你把 `.header-big #search-text` 的 `background-color` 属性去掉就可以了~ ![image](https://user-images.githubusercontent.com/26101369/220817082-a7f32e98-62bc-4777-8ce0-30daee3d478b.png)

在 `\static\assets\css\style-3.03029.1.css` 里面的 `.header-big #search-text` 这一行里删除 `;background-color:rgba(0,0,0,0.6)!important` 再在当前行里将 `color:#fff` 换成 `color:#6C757D` 即可重现"搜索栏跟随’夜间模式‘变化”

**Comment by shenweiyan** [comment]
刚刚提交了一个[新版本](https://github.com/shenweiyan/WebStack-Hugo/commit/5718cc6924b572cfa5603a845b991062df4552a2)，增加了对搜索位置不设置背景图的样式适应支持 >.<

现在只需要在 `config.toml` 中把 `searchImageL` 和 `searchImageD` 都设置为空就可以了~
