### ISSUE TITLE
如何将深色背景设置为默认？

### ISSUE THREAD

**Issue by JeamUmika** [shenweiyan/WebStack-Hugo#13]
想将深色背景设置为默认但又不知修改哪个地方

![图片](https://user-images.githubusercontent.com/93057377/220914833-496e32d3-5994-4559-b5e2-4978dd0af460.png)

**Comment by JeamUmika** [comment]
通过暴力修改实现了把深色模式改为默认
源码：https://github.com/JeamUmika/WebStack-Hugo
demo：https://box.jeam.cc

**Comment by shenweiyan** [comment]
> 通过暴力修改实现了把深色模式改为默认 源码：https://github.com/JeamUmika/WebStack-Hugo demo：https://box.jeam.cc

挺好的，默认主题的确是个好问题，或许应该增加一个设置默认主题的配置参数，有空我看看能不能实现

**Comment by JeamUmika** [comment]
> > 通过暴力修改实现了把深色模式改为默认 源码：https://github.com/JeamUmika/WebStack-Hugo demo：https://box.jeam.cc
> 
> 挺好的，默认主题的确是个好问题，或许应该增加一个设置默认主题的配置参数，有空我看看能不能实现

里面有个夜间时自动切换到夜间模式的函数，好像不生效

**Comment by JeamUmika** [comment]
> > 通过暴力修改实现了把深色模式改为默认 源码：https://github.com/JeamUmika/WebStack-Hugo demo：https://box.jeam.cc
> 
> 挺好的，默认主题的确是个好问题，或许应该增加一个设置默认主题的配置参数，有空我看看能不能实现

里面有个夜间时自动切换到夜间模式的函数，好像不生效

**Comment by shenweiyan** [comment]
说实在的，我对 js 不是很懂，所有夜间/白天模式的这个切换个人改的也不是很好，一直希望能有个略懂 js 的人能帮忙弄一下

**Comment by JeamUmika** [comment]
> 说实在的，我对 js 不是很懂，所有夜间/白天模式的这个切换个人改的也不是很好，一直希望能有个略懂 js 的人能帮忙弄一下

很遗憾不能帮到你，因为我不是计算机专业的，没怎么学过前端

**Comment by shenweiyan** [comment]
刚刚提交了一个[新版本](https://github.com/shenweiyan/WebStack-Hugo/commit/035d0c6a0e586e5bc384b0c7679492f3a81a2d4d)，现在选择日间还是夜间模式作为默认已经可以通过 `config.toml` 文件的 `nightMode` 参数一键化配置实现了 >.<
