### ISSUE TITLE
关于页面没有样式

### ISSUE THREAD

**Issue by moxv** [shenweiyan/WebStack-Hugo#14]
貌似关于页面丢失了样式，没有样式了

**Comment by shenweiyan** [comment]
我这边是正常的。
欢迎截图，或者提交预览站点（私信给我也行），否则没法知道哪里出问题了~

**Comment by moxv** [comment]
> 我这边是正常的。 欢迎截图，或者提交者提交预览站点（私信给我也行），否则不知道哪里出问题了~
![](https://img1.imgtp.com/2023/02/28/BhpQYeVq.png)

**Comment by shenweiyan** [comment]
这个应该是 about 页面吧，目前 about 这些单页面目前还没有做样式适应。

如果可以，也欢迎你来折腾 PR 分享一下，感谢~

**Comment by moxv** [comment]
> 这个应该是 about 页面吧，目前 about 这些单页面目前还没有做样式适应。
> 
> 如果可以，也欢迎你来折腾 PR 分享一下，感谢~

我小白，那请教大佬这个页面的css再哪里，我试试

**Comment by shenweiyan** [comment]
这个页面对应 `layouts/_default/single.html` 这个文件，新增加的 css 可以放到`static/assets/css/custom-style.css`，或者创建一个`static/assets/css/single.css`单独存放也可以~
