### ISSUE TITLE
[功能请求]网址导航分页显示

### ISSUE THREAD

**Issue by AndaBrown** [shenweiyan/WebStack-Hugo#17]
如题。

当网站收录的网址较多时，会造成HTML过长，不利于搜索引擎seo优化。同时，也会拖慢加载速度，影响访客体验。

目前想到的办法有两种：
1. 按照链接数量裁断（需要额外判定一下，当前类别显示完，防止拦腰斩断），达到分页显示的目的。
2. 每个类别新增一个分页，在网址导航首页随机显示8个该类别的链接，并且在每个类别新增一个 查看更多 按钮（我看源码里面好像有个more+注释掉了，不知道有没有类似的功能）。

个人倾向于第二种，不知道这个功能好不好实现？大佬有没有类似的想法？
（我就是瞎提点建议，具体怎么写全靠大佬安排）

**Comment by shenweiyan** [comment]
想法很好！
现在的版本对于我来说是够用且还能接受的，但个人精力有限，同样希望有相同想法的大佬可以去折腾一下~
再次感谢~
