### ISSUE TITLE
所有页面的样式都丢失了

### ISSUE THREAD

**Issue by scutLMG** [shenweiyan/WebStack-Hugo#18]
现在放在这：https://scutlmg.github.io/torchNavi/
我也不知道为啥？
本地hugo server 预览是没有问题的，上传githubpageyihou就不行了
我的部署action是用peaceiris/actions-gh-pages@v3
是因为部署的方式不一样影响了生成吗？

**Comment by scutLMG** [comment]
[scutLMG](https://github.com/scutLMG)
/
[torchNavi](https://github.com/scutLMG/torchNavi)这是开源仓库
部署分支是gh-pages，主分支（源代码分支）是main

**Comment by scutLMG** [comment]
页面如图
![website](https://user-images.githubusercontent.com/45113495/224573701-accdc4b9-0b58-419c-9a0b-3a99149336f1.png)
大概找到原因了
![bug](https://user-images.githubusercontent.com/45113495/224573720-9789f76d-450a-46b3-8539-d50082d69d03.png)

查看样式引用路径，是如 `href="/assets/css/block-library.min-5.6.2.css"` 这样的，我感觉可能是引用有问题。全改成 `href="./assets/css/..."` 如下图后

![fixed](https://user-images.githubusercontent.com/45113495/224573730-b46ace3e-0be1-47df-aeae-9b13bde842c3.png)
部分样式就重现了，但是js和背景图片依旧没有加载出来，
**现在的问题变成，我该在哪里修改引用路径了，没找到地方改**

**Comment by shenweiyan** [comment]
你现在站点 css/js 的路径应该是指向了 `https://scutlmg.github.io/assets/` 这个目录；但事实上你真实的 css/js 应该位于 `https://scutlmg.github.io/torchNavi/assets/` 目录，所以导致了 404（File not found）从而不起作用。

https://github.com/shenweiyan/WebStack-Hugo/pull/15 这一次的提交对静态资源引用的方式作了调整，现在发现还有点问题，晚点我修复一下。

**Comment by shenweiyan** [comment]
已经更新了最新的代码，现在重新部署一下应该就没问题了~

**Comment by scutLMG** [comment]
> 你现在站点 css/js 的路径应该是指向了 `https://scutlmg.github.io/assets/` 这个目录；但事实上你真实的 css/js 应该位于 `https://scutlmg.github.io/torchNavi/assets/` 目录，所以导致了 404（File not found）从而不起作用。
> 
> #15 这一次的提交对静态资源引用的方式作了调整，现在看来还有点问题的，晚点我修复一下。

是的，我后来也意识到了，前端学得烂，不咋会，还打算今天再搞搞咧，谢谢大哥了，回去我试试。

**Comment by scutLMG** [comment]
好的，问题解决啦，不过如果是这样的话，预览或者一级目录可能就不起效了，其实你告诉我在哪改就行啦，你改了以后其他人不知会否出问题。

**Comment by shenweiyan** [comment]
> 好的，问题解决啦，不过如果是这样的话，预览或者一级目录可能就不起效了，其实你告诉我在哪改就行啦，你改了以后其他人不知会否出问题。

更改后对于纯域名和包含子目录的域名都能更好的适应了 >.<

![https://gohugo.io/functions/relurl/](https://user-images.githubusercontent.com/26101369/224864256-f4453341-71b8-41cf-8ae5-48ff957d1742.png)
