### ISSUE TITLE
链接的图标该放在哪个文件？如何渲染加载的？

### ISSUE THREAD

**Issue by scutLMG** [shenweiyan/WebStack-Hugo#19]
你好，我更新了一些链接，也上传了图标，没有加载出图标，我想修改一下，但是我对go,hugo都不甚了解。
图标是放置在根目录的 `assets/images` 还是 `static/images`，还是 `theme/webstack-hugo/assets/iamges` ？
我每一个都复制了一轮，因为放在 `assets` 下的全都没通过 action 部署到 `gh-pages` 分支，后来我新建了 `static/images` 后就在 `gh-page`s 分支有文件更新了，但是网站内并没有刷新图标，我尝试清理缓存刷新也没响应，都是显示的 default.png ，不知是如何识别并渲染的？
但我旧的网页图标（没创建 `static` 之前，都是塞在 `assets` 里的）都是可以识别加载出来的。这是否和 action 或者文件路径有关系？

**Comment by shenweiyan** [comment]
`config.toml` 写了：
```
logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
```
所以，这些 logo 图标是放在更目录的 `static/assets/images/logos` 目录下就可以了，你也可以参考一下 [BioWebStack](https://github.com/bioitee/BioWebStack) 这个项目，这是一个比较完整的示例。

**Comment by scutLMG** [comment]
是的，我就是疑惑是否要在前面有 `static/..` ，因为似乎原版的 hugo 下的文件目录是 `assets` ，我在里面加没有什么反应，现在测试了以后渲染生效了，谢谢解答！
