### ISSUE TITLE
强烈推荐建议适配chrome书签json结构，方便一键导出生成

### ISSUE THREAD

**Issue by fulige18** [shenweiyan/WebStack-Hugo#2]
如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。如果可以适配一下，我觉得效率简直不要太高，门槛又低。
现有我发现的有2款插件：
一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url)
一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url)
。另外大佬要是能支持子分类就更完美了。看了下好像手机上没做自适应

**Comment by shenweiyan** [comment]
> 如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。如果可以适配一下，我觉得效率简直不要太高，门槛又低。 现有我发现的有2款插件： 一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url) 一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url) 。另外大佬要是能支持子分类就更完美了。看了下好像手机上没做自适应

1. 你是想把 chrome 书签用在现在的导航上，对 chrome 书签增删改来实现对导航的增删改？
2. 支持分类值得是什么意思？目前只在左侧导航栏有子分类。
3. 手机上没做自适应？我在手机上打开 https://nav.bioitee.com/ 是正常的。
![20220420110822](https://user-images.githubusercontent.com/26101369/164142611-630a61e8-111c-4cc5-9b34-6274aac310e0.jpg)

**Comment by fulige18** [comment]
> > 如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。如果可以适配一下，我觉得效率简直不要太高，门槛又低。 现有我发现的有2款插件： 一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url) 一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url) 。另外大佬要是能支持子分类就更完美了。看了下好像手机上没做自适应
> 
> 1. 你是想把 chrome 书签用在现在的导航上，对 chrome 书签增删改来实现对导航的增删改？
> 2. 支持分类值得是什么意思？目前只在左侧导航栏有子分类。
> 3. 手机上没做自适应？我在手机上打开 https://nav.bioitee.com/ 是正常的。
>    ![20220420110822](https://user-images.githubusercontent.com/26101369/164142611-630a61e8-111c-4cc5-9b34-6274aac310e0.jpg)

哇，没想到真能得到大佬回复。
1.是的，就是可以根据我chrome书签的结构，分类，数据一键生成。不用单独在某个文件里去增删。直接在chrome书签里增删然后一键导出覆盖这种形式。因为习惯是周期性批量增删导出一次，不会增删一两个书签就导出一次。
2.抱歉，刚看了下，我之前没注意分类形式。看了下是支持子分类的。
3.适配也是正常的。之前可能看错了
主要是第1点，实现了就吹爆了

**Comment by shenweiyan** [comment]
@fulige18 想法挺好的，但是实现起来可能相对麻烦一些
现在的功能基本可以满足我个人的使用需求了，你提到的这个新功能目前是没有精力去折腾了，你也可以自己去开发一下，再次感谢~

**Comment by shenweiyan** [comment]
推荐一个可以将收藏夹里面的书签，展示在浏览器默认主页上的插件工具：[小舒同学](https://xiaoshu.app/)

![image](https://user-images.githubusercontent.com/26101369/169427676-3a678fdd-cfef-4603-bdeb-87aa1fe29c75.png)
