### ISSUE TITLE
代码结构调整

### ISSUE THREAD

**Issue by cn-src** [shenweiyan/WebStack-Hugo#20]
你好，我试了下搭建，在一个 hugo 工程中，步骤是：

1. 初始化 hugo 工程
2. 把 exampleSite 里的内容放在工程根目录
3. 把整个 WebStack-Hugo 放在工程的 themes 目录

第一次搭建这个目录移动让我有点懵，不能开箱即用。

我在想是不是直接就弄成一个可以直接使用的结构即可，不用再去移动目录，然后：

1. 把原有的 webstack.yml 命名成 webstack.template.yml，这样不影响使用者用 webstack.yml。
2. 把这个仓库设置为一个 Github 模板仓库。

这样只要装好 hugo 就能开箱即用了。

**Comment by shenweiyan** [comment]
hugo 主题好像都是这个样子吧，第一次会稍微麻烦一点点~
