### ISSUE TITLE
hugo -D 问题

### ISSUE THREAD

**Issue by 541013515** [shenweiyan/WebStack-Hugo#21]
hugo server 后能正常访问，但是访问的路径是：http://localhost:1313/WebStack-Hugo，相比教程里多了WebStack-Hugo这个context root

hugo -D 生成的 public 目录，访问 index.html 会出现元素没法加载的情况，感觉就是这个 WebStack-Hugo 影响了

是哪里需要配置下么?

**Comment by shenweiyan** [comment]
能问一下是什么元素没法加载吗？

**Comment by yimao009** [comment]
我的也是， hugo server 正常访问，  hugo -D 生成的public里的index预览，样式缺少
![1234](https://github.com/shenweiyan/WebStack-Hugo/assets/15336414/2157a8f8-a42a-4b81-805e-6aac02a17bad)

**Comment by shenweiyan** [comment]
> 我的也是， hugo server 正常访问， hugo -D 生成的public里的index预览，样式缺少 ![1234](https://user-images.githubusercontent.com/15336414/277895536-2157a8f8-a42a-4b81-805e-6aac02a17bad.png)

https://github.com/shenweiyan/WebStack-Hugo/issues/24，参考一下这里的教程

**Comment by lxong8** [comment]
hugo -D 的时候提示：WARN found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination
然后最终样式就如楼上的图示

**Comment by shenweiyan** [comment]
> hugo -D 的时候提示：WARN found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination 然后最终样式就如楼上的图示

WARN 的信息不影响使用，可以不需要额外处理；对于样式不显示，请参考 https://github.com/shenweiyan/WebStack-Hugo/issues/24，或者拉取最新的代码重新部署一下试试。

**Comment by shenweiyan** [comment]
> hugo -D 的时候提示：WARN found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination 然后最终样式就如楼上的图示

WARN 的信息不影响使用，可以不需要额外处理；对于样式不显示，请参考 https://github.com/shenweiyan/WebStack-Hugo/issues/24，或者拉取最新的代码重新部署一下试试。
