### ISSUE TITLE
如何在 Vercel 上自动部署

### ISSUE THREAD

**Issue by woshichenghaibo** [shenweiyan/WebStack-Hugo#22]
fork了一份，修改了config，但是还是空白 

https://nav.fewknown.com/

**Comment by shenweiyan** [comment]
有可能是你的 `webstack.yml` 这个文件格式出什么问题了？

[https://shenweiyan.github.io/WebStack-Hugo/](https://shenweiyan.github.io/WebStack-Hugo/) 这个是基于这个 main 进行构建的，目前是正常的。

**Comment by woshichenghaibo** [comment]
> 有可能是你的 `webstack.yml` 这个文件格式出什么问题了？
> 
> https://shenweiyan.github.io/WebStack-Hugo/ 这个是基于这个 main 进行构建的，目前是正常的。

我就是不修改，完全原版fork，也是显示空白

**Comment by shenweiyan** [comment]
有仓库地址吗？

**Comment by woshichenghaibo** [comment]
> 有仓库地址吗？

https://github.com/woshichenghaibo/WebStack-Hugo/tree/main

**Comment by woshichenghaibo** [comment]
> 有仓库地址吗？

你可以在vercel部署一下试试

**Comment by woshichenghaibo** [comment]
> 有仓库地址吗？

https://hugonav.fewknown.com/

这是我在vercel上面部署后的效果

**Comment by shenweiyan** [comment]
你在 vercel 上是怎么部署的？

**Comment by woshichenghaibo** [comment]
> Vercel 上不能使用 hugo 框架直接部署这个仓库（因为这只是一个主题仓库），需要：
> 
> 1. 创建一个文件，名为 mysite（名字可以自取）；
> 2. 在 mysite 目录中创建一个 themes 目录，然后再把 https://github.com/shenweiyan/WebStack-Hugo 这个主题放到 themes 目录下；
> 3. 把 themes/WebStack-Hugo/exampleSite 目录下的内容全部复制到 mysite 下面；
> 4. 最后，把 mysite 整个目录上传到 Vercel，然后使用  hugo 框架直接部署就可以了。
> 
> 这就跟 Windows 下的部署是一样的。
> 
> 如果想要直接部署仓库的话，可以参考 https://github.com/shenweiyan/NavBioIT 这个项目，你可以直接 clone 这个仓库，然后把一些信息修改成你的，就可以在 Vercel 上部署了。

已部署，谢谢。

右侧搜索按钮要是能作为站内搜索功能就好了，比如我点开搜索  词典，就会找到我网页内的词典的网址收藏，而不是现在的搜索引擎搜索
