### ISSUE TITLE
静态生成相对路径问题

### ISSUE THREAD

**Issue by Lonely-Sit** [shenweiyan/WebStack-Hugo#23]
![屏幕截图 2023-05-01 102440](https://user-images.githubusercontent.com/71547798/235393825-fa935623-3613-44e4-a4ad-2771ddd96bdd.png)
![屏幕截图 2023-05-01 103618](https://user-images.githubusercontent.com/71547798/235393858-d86a2124-f004-4eb1-8f81-0e88030819c9.png)

**Comment by shenweiyan** [comment]
关于样式不显示的问题，可以通过下面的方法检查一下：

1. 检查一下 hugo 的版本，建议使用 https://github.com/gohugoio/hugo/releases/v0.89.4/ 的版本；有用户反馈太高的 hugo 版本也可能会造成样式不显示。

2. 如果`hugo server`正常，但`hugo -D`生成的`public/index.html`生成的静态文件**直接在浏览器打开**出现样式不显示：
   - 正常`hugo -D`生成的`public`静态文件需要上传到 github pages/[Cloudflare Pages](https://pages.cloudflare.com/)，通过 url 才能正常显示，本地是无法直接查看。
   
   - 如果想要实现本地直接查看，可以在`config.toml`文件的顶部添加一个`relativeURLs = true`的选项，`hugo -D`重新生成一下`public`静态文件即可。 ![image](https://user-images.githubusercontent.com/26101369/236094428-0edfb9bb-0512-4e79-9e48-491fb4dc7bd4.png)
