### ISSUE TITLE
关于页面样式和路径的问题

### ISSUE THREAD

**Issue by shenweiyan** [shenweiyan/WebStack-Hugo#24]
**关于路径的问题：**

1. 如果你的`baseURL  = "https://example.com/WebStack"`（多了一个子目录`WebStack` ），本地预览时需要在浏览器中打开 http://127.0.0.1:1313/WebStack 进行预览；![image](https://user-images.githubusercontent.com/26101369/236096515-fa916d77-2944-453a-b27d-b9dc5ea704b5.png)

2. 如果你的`baseURL  = "https://example.com/`（不带子目录），本地预览在浏览器中打开 http://127.0.0.1:1313 即可。
![image](https://user-images.githubusercontent.com/26101369/236096773-2545fdd6-7e16-44db-bc48-2b52ec63efe5.png)

------

**关于样式不显示的问题，可以通过下面的方法检查一下：**

1. 检查一下 hugo 的版本，建议使用 https://github.com/gohugoio/hugo/releases/v0.89.4/ 的版本；有用户反馈太高的 hugo 版本也可能会造成样式不显示。

4. 如果`hugo server`正常，但`hugo -D`生成的`public/index.html`生成的静态文件**直接在浏览器打开**出现样式不显示：
   - 正常`hugo -D`生成的`public`静态文件需要上传到 github pages/[Cloudflare Pages](https://pages.cloudflare.com/)，通过 url 才能正常显示，本地是无法直接查看。
   
   - 如果想要实现本地直接查看，可以在`config.toml`文件的顶部添加一个`relativeURLs = true`的选项，`hugo -D`重新生成一下`public`静态文件即可。 ![image](https://user-images.githubusercontent.com/26101369/236094428-0edfb9bb-0512-4e79-9e48-491fb4dc7bd4.png)

**Comment by hangzhi7** [comment]
**关于样式不显示的问题，我的调试了一下，最后的解决办法：**  将主题中的所有 “relURL”全部去掉就可以，用github pages部署也能正常访问

- 其实样式问题可以通过浏览器开发者模式控制台发现，是样式没有加载到包404，是路径问题，与hugo 的版本没有关系，

<img width="884" alt="image" src="https://github.com/shenweiyan/WebStack-Hugo/assets/25549771/d8440ffa-422f-4aa1-9404-62320f3042b8">
如上图，如果有relURL 生成时 路径里会多一个 “ / ”，这样的样式加载都会报404的，看作者github pages 部署示例也是样式有问题的，地址查看：https://shenweiyan.github.io/NavBioIT/ ，我也不知道为什么用Cloudflare Pages部署就可以正常访问。

- 其实github pages 部署后访问和本地用 `hugo -D`生成的`public/index.html`生成的静态文件**直接在浏览器打开**是一样的原理

**Comment by tom2almighty** [comment]
将 `layouts/partials` 文件夹下文件中 `relURL` 更换为 `absURL` 也可。

**Comment by shenweiyan** [comment]
> 将 `layouts/partials` 文件夹下文件中 `relURL` 更换为 `absURL` 也可。

感谢，已经把下面的 `relURL` 都更换为 `absURL` 了。

**Comment by yaoyuanArtemis** [comment]
> https://shenweiyan.github.io/NavBioIT/

为什么我这个文件夹下是空的

**Comment by my-youth** [comment]
> 将 `layouts/partials` 文件夹下文件中 `relURL` 更换为 `absURL` 也可。

我的文件里面里面已经是absURL了，但是hugo -D生成的文件本地和GitHub pages部署后都没法显示图标

**Comment by shenweiyan** [comment]
> > https://shenweiyan.github.io/NavBioIT/
> 
> 为什么我这个文件夹下是空的

NavBioIT 仓库已经更改为 <https://github.com/shenweiyan/Bioit-top>，对应访问链接：<https://bioit.top/>。

**Comment by Xm798** [comment]
站点在二级目录时，即 `baseUrl = https://example.org/docs/` 时，站点图标加载存在问题，应当为图标的 src 也添加 absURL/relURL。
