### ISSUE TITLE
代码小白：hugo: command not found

### ISSUE THREAD

**Issue by Ju9aad** [shenweiyan/WebStack-Hugo#27]
代码小白：这东西怎么弄啊，怎么这么复杂

**Comment by shenweiyan** [comment]
你的 hugo 还没有安装，你需要先安装一下 hugo

**Comment by makessr** [comment]
就原本的这个问题，我写了一个关于docker来搭建Webstack-Hugo的教程。

链接在这里：[https://www.salanghe.com/technology/2289.html](url)
