### ISSUE TITLE
custom-style.css中，About页面的超链接颜色定义无效

### ISSUE THREAD

**Issue by Mrkuiku** [shenweiyan/WebStack-Hugo#28]
custom-style.css中， About页面的超链接颜色定义无效。

/*About页面*/
.panel .panel-body a {color: #007bff;}
.panel .panel-body a:hover {color: #979898;}

**Comment by shenweiyan** [comment]
About 页面目前没有做 css 渲染，我已经搞不动了，这方面的 css 还请自己去折腾啦 >.<
