### ISSUE TITLE
大佬，可以增加站内搜索吗？

### ISSUE THREAD

**Issue by luolovehk** [shenweiyan/WebStack-Hugo#3]
还有就是手机端的，右上角有搜索按钮、右下角有，页面也有搜索，太多了吧~~

**Comment by shenweiyan** [comment]
> 还有就是手机端的，右上角有搜索按钮、右下角有，页面也有搜索，太多了吧~~

你可以把右下角的搜索按钮注释掉，后续我看能不能在配置文件中增加一个开启/关闭右下角搜索的选项

**Comment by shenweiyan** [comment]
站内搜索我暂时就没时间折腾了，不好意思；或者你也可以尝试去弄一下

**Comment by luolovehk** [comment]
你好，请教一下，如果移动端也需要显示 tooltip 标签，要怎么修改。

**Comment by shenweiyan** [comment]
> 你好，请教一下，如果移动端也需要显示 tooltip 标签，要怎么修改。

显示 tooltip 标签，这个具体指的是什么？

**Comment by luolovehk** [comment]
https://iplaycode.github.io/nav/
参照这个主题，移动端点击会显示这个标签。
我已经在你的主题上加了二维码演示功能，可是移动端点击不显示这个提示标签

![image](https://user-images.githubusercontent.com/61071476/184759291-35547f19-7bc3-49fb-9f00-3b05ed8fcc1e.png)
![image](https://user-images.githubusercontent.com/61071476/184759318-e011facf-5eca-40c9-97ba-26e7fe1f1228.png)

**Comment by shenweiyan** [comment]
> https://iplaycode.github.io/nav/ https://github.com/iplaycode/webstack-hugo 参照这个主题，移动端点击会显示这个标签。 我已经在你的主题上加了二维码演示功能，可是移动端点击不显示这个提示标签
> 
> ![image](https://user-images.githubusercontent.com/61071476/184759291-35547f19-7bc3-49fb-9f00-3b05ed8fcc1e.png) ![image](https://user-images.githubusercontent.com/61071476/184759318-e011facf-5eca-40c9-97ba-26e7fe1f1228.png)

https://github.com/iplaycode/webstack-hugo 这个主题在`layouts/index.html`里面增加了一个`qrcode`的判断；

参考它的做法，你也可以在 https://github.com/shenweiyan/WebStack-Hugo 主题的 `layouts/partials/content_main.html` 也增加一个类似`qrcode`的判断，然后在`data/webstack.yml`对单个导航增加一个`qrcode`参数（如下所示）应该就可以了：
```
- title: 二维码演示
      qrcode: assets/images/webstack-hugo-qrcode.png
      logo: assets/images/favicon.png
      description: 二维码演示，新增二维码，手机扫一扫
```

**Comment by luolovehk** [comment]
这个功能已经添加成功的了。
PC端移动鼠标经过能够正常显示：
![image](https://user-images.githubusercontent.com/61071476/184783920-c4b1826e-35c7-4110-a71e-82e411e68a4f.png)

移动端点击，标签没显示出来。
![image](https://user-images.githubusercontent.com/61071476/184783999-a7b0cdb3-1e69-4cca-b5c0-417d994bcf1e.png)

我想在移动端也可以显示这个标签

**Comment by shenweiyan** [comment]
正常来说 PC 端没问题，移动端应该也可以的，方便的话可以加个微信（我的微信号：ishenweiyan），把你的站点发给我看一下
