### ISSUE TITLE
发现无法新增链接，不知道是什么问题。

### ISSUE THREAD

**Issue by makessr** [shenweiyan/WebStack-Hugo#31]
复现：在webstack.yml上，新增链接保存之后，重启docker。首页就会出现502状态。删除新增的链接就不会

不知道这是什么问题。

还是说必须按照原webstack.yml原有的链接数量才行。

**Comment by makessr** [comment]
并不行，我直接在服务器上弄的，修改文件后还是会出现。

**Comment by makessr** [comment]
<img width="873" alt="image" src="https://github.com/shenweiyan/WebStack-Hugo/assets/46600469/7bc9d196-936c-4d49-b80c-31e6708493ec">
最后三个链接是新增的。更新后打不开502状态，删除就正常。

**Comment by psych-future** [comment]
或许是你的代码没有进行空格，或者中英文使用混淆了？建议删除最后三个链接，然后复制上面的链接代码到下面看看。
![image](https://github.com/shenweiyan/WebStack-Hugo/assets/56164130/47de43d7-bfb9-4c32-a8da-03bfded2b395)
![image](https://github.com/shenweiyan/WebStack-Hugo/assets/56164130/b169f015-6f80-455f-8926-76c941f2d522)
