### ISSUE TITLE
导航站不错，老司机导航加个友链laosji.net

### ISSUE THREAD

**Issue by laosji** [shenweiyan/WebStack-Hugo#33]
如题加个友链：
1、laosji.net
2、itianxia.cn

**Comment by shenweiyan** [comment]
已加 <https://itianxia.cn/>，也请帮忙加一个 <https://bioit.top/>，感谢~

**Comment by laosji** [comment]
已经添加，谢谢
[image: image.png]

Steven Shum ***@***.***> 于2023年8月3日周四 22:34写道：
