### ISSUE TITLE
增加公告模块

### ISSUE THREAD

**Issue by zs6** [shenweiyan/WebStack-Hugo#34]
![image](https://github.com/shenweiyan/WebStack-Hugo/assets/45552564/5dcb0aa3-657e-4444-93af-b5675346507a)

如图，希望可以增加一个公告模块，类似所长导航的这样

**Comment by shenweiyan** [comment]
这个模块是有的，只不过我注释掉了，需要的话可以去这里面把注释去掉就可以了。
https://github.com/shenweiyan/WebStack-Hugo/blob/23fe234f9d183292241acabef0bd85320edef5f1/layouts/partials/content_search.html#L240

**Comment by zs6** [comment]
我感觉做成可配置的选项比较好

**Comment by shenweiyan** [comment]
> 我感觉做成可配置的选项比较好

来来来，欢迎大佬集成一下~
