### ISSUE TITLE
备案查询的链接地址，如何修复

### ISSUE THREAD

**Issue by h31105** [shenweiyan/WebStack-Hugo#38]
https://icp.aizhan.com:6666/xxx.xxx.xx/
修改为
https://icp.aizhan.com/xxx.xxx.xx/
去掉端口就正常了

但是代码中没找到对应上述内容的修改位置
请帮忙看一下

**Comment by shenweiyan** [comment]
这个的确有点奇怪，代码中写的是`https://icp.aizhan.com/xxx.xxx.xx/`，没搞明白它这个 `6666` 端口是怎么加上去的。。。
