### ISSUE TITLE
关于适配子文件夹

### ISSUE THREAD

**Issue by slske** [shenweiyan/WebStack-Hugo#41]
您好，关于适配子文件夹，改我倒是会改，我研究了一下发现除了配置文件以外，只需要再改以下两个文件就能适配
WebStack-Hugo\layouts\partials\footer.html
WebStack-Hugo\layouts\partials\header.html
我只是提个建议，打扰了。

**Comment by slske** [comment]
哦，还有，你这个主题我导出原版静态文件，发现居然有30M，感觉挺大的。

**Comment by slske** [comment]
> > 您好，关于适配子文件夹，改我倒是会改，我研究了一下发现除了配置文件以外，只需要再改以下两个文件就能适配 WebStack-Hugo\layouts\partials\footer.html WebStack-Hugo\layouts\partials\header.html 我只是提个建议，打扰了。
> 
> 有点没弄明白适配子文件夹指的是？

xxx.com/导航/
类似于这个格式

**Comment by shenweiyan** [comment]
> 哦，还有，你这个主题我导出原版静态文件，发现居然有30M，感觉挺大的。

`static/assets` 下的 fontawesome-5.15.4 就有 20M；images 导航图标有差不多 10M，如果不需要可以删除，换成在线的资源。

**Comment by shenweiyan** [comment]
> > > 您好，关于适配子文件夹，改我倒是会改，我研究了一下发现除了配置文件以外，只需要再改以下两个文件就能适配 WebStack-Hugo\layouts\partials\footer.html WebStack-Hugo\layouts\partials\header.html 我只是提个建议，打扰了。
> > 
> > 
> > 有点没弄明白适配子文件夹指的是？
> 
> xxx.com/导航/ 类似于这个格式

现在子目录应该也是支持的，例如 <https://shenweiyan.github.io/WebStack-Hugo/>，如有更好的方法，欢迎 PR，再次感谢 >.<

**Comment by slske** [comment]
我的锅，那就是我没弄懂配置，抱歉，打扰了。0.0
