### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by INFPOSS** [shenweiyan/WebStack-Hugo#46]
1.在config设置默认展开导航栏后，导航栏动画在桌面端会失效。2.我该如何设置一行内最多可显示多少链接

**Comment by shenweiyan** [comment]
1. 桌面端失效指的是本地 http://127.0.0.1:1313 下失效？另外"导航栏动画"指的是什么？
   我测试了一下，暂时没发现你所说的问题。

2. 一行内最多可显示多少链接是根据你的浏览器宽度响应式自动适应的，如果你要调整，需要手动去 `layouts/partials/content_main.html` 中调整相关代码。 
   同时建议参考一下 Bootstrap 网格系统的一些用法。

**Comment by shenweiyan** [comment]
> > 1. 桌面端失效指的是本地 http://127.0.0.1:1313 下失效？另外“导航栏动画”指的是什么？ 我测试了一下，暂时没发现你所说的问题。
> > 2. 一行内最多可显示多少链接是根据你的浏览器宽度响应式自动适应的，如果你要调整，需要手动去  中调整相关代码。
> >    同时建议参考一下 Bootstrap 网格系统的一些用法。`layouts/partials/content_main.html`
> 
> 导航栏动画，就是在hugo的config里设置默认展开导航栏后，在桌面端打开网站时，在点击导航栏收起/展开的按钮后，导航栏的收起/展开动画会消失，直接展开/收起了，之前的展开/收起动画是有的

非常感谢你热心的回复。但非常抱歉，我还是不太理解这个动画是指哪一个动画，如果方便麻烦截个图看看 >.<
个人的理解是点击导航栏收起/展开的按钮后，只会对左侧导航栏起到收起/展开的作用，应该是没有其他的动画了。
![image](https://github.com/shenweiyan/WebStack-Hugo/assets/26101369/f1197c0e-1171-48db-8a22-bf7f969bbf6e)

**Comment by shenweiyan** [comment]
点击导航栏收起/展开按钮，能正常收起或者展开左侧导航栏吗？你的站点地址是什么，能不能发过来看一下？
