### ISSUE TITLE
页面内搜索功能，供参考

### ISSUE THREAD

**Issue by woshichenghaibo** [shenweiyan/WebStack-Hugo#47]
Hi，我是 Kimi，很高兴遇见你！
应用商店搜索 “Kimi 智能助手”
随时和 Kimi 聊天！

编写一张网页源代码，实现页面内搜索功能。有一个文本框，文本框右侧有一个搜索按钮，在文本框输入关键词后按下回车键或者点击搜索按钮，即可实现页面内搜索并高亮显示关键词。
创建一个简单的网页，实现页面内搜索并高亮显示关键词的功能，可以通过HTML、CSS和JavaScript来完成。以下是一个基本的示例代码：
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>页面内搜索</title>
<style>
    .highlight {
        background-color: yellow;
    }
</style>
</head>
<body>

<h1>页面内搜索示例</h1>

<input type="text" id="searchBox" placeholder="输入关键词" />
<button onclick="search()">搜索</button>

<div id="content">
    这是一个示例文本，您可以在这段文本中搜索关键词。搜索功能将高亮显示所有匹配的关键词。
</div>

<script>
    let currentSearchTerm = null;

    function search() {
        const searchTerm = document.getElementById('searchBox').value;
        if (searchTerm === currentSearchTerm) return; // 如果搜索词没有变化，不执行搜索
        currentSearchTerm = searchTerm;

        const contentDiv = document.getElementById('content');
        const content = contentDiv.innerHTML;
        const regex = new RegExp(searchTerm, 'gi'); // 创建一个全局忽略大小写的正则表达式

        // 如果搜索词不为空，则高亮显示匹配的关键词
        if (searchTerm) {
            contentDiv.innerHTML = content.replace(regex, `<span class="highlight">$&</span>`);
        } else {
            contentDiv.innerHTML = content; // 如果搜索词为空，恢复原始内容
        }
    }

    // 监听回车键
    document.getElementById('searchBox').addEventListener('keyup', function(event) {
        if (event.key === 'Enter') {
            search();
        }
    });
</script>

</body>
</html>

这个示例中：

HTML部分定义了一个输入框和一个搜索按钮。
CSS部分定义了一个.highlight类，用于高亮显示搜索关键词。
JavaScript部分定义了一个search函数，当用户输入关键词并点击搜索按钮或按下回车键时，该函数会被调用。
该函数使用正则表达式来查找输入的关键词，并将其包装在<span>标签中，同时应用.highlight类以高亮显示。
还添加了一个事件监听器，以便在用户按下回车键时也能触发搜索功能。
请将上述代码保存为.html文件，并在浏览器中打开以查看效果。

**Comment by woshichenghaibo** [comment]
修改以上代码，使得如何无搜索结果，则页面无反应。如果有匹配搜索结果，则将页面焦点立即跳转到第一个搜索结果。

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>页面内搜索</title>
<style>
    .highlight {
        background-color: yellow;
        cursor: pointer;
    }
</style>
</head>
<body>

<h1>页面内搜索示例</h1>


<input type="text" id="searchBox" placeholder="输入关键词" />
<button onclick="search()">搜索</button>


<div id="content">
    这是一个示例文本，您可以在这段文本中搜索关键词。搜索功能将高亮显示所有匹配的关键词。
</div>

<script>
    let currentSearchTerm = null;

    function search() {
        const searchTerm = document.getElementById('searchBox').value.trim();
        if (searchTerm === '') {
            // 清空搜索词，恢复原始内容
            document.getElementById('content').innerHTML = originalContent;
            currentSearchTerm = null;
            return;
        }

        if (searchTerm === currentSearchTerm) return; // 如果搜索词没有变化，不执行搜索

        currentSearchTerm = searchTerm;
        const contentDiv = document.getElementById('content');
        const regex = new RegExp(`(${searchTerm})`, 'gi'); // 创建一个全局忽略大小写的正则表达式

        // 存储原始内容
        if (!originalContent) {
            originalContent = contentDiv.innerHTML;
        }

        const newContent = contentDiv.innerHTML.replace(regex, `<span class="highlight">$1</span>`);

        // 如果新内容与原始内容相同，说明没有搜索结果
        if (newContent === originalContent) {
            alert('未找到匹配的关键词。');
            return;
        }

        contentDiv.innerHTML = newContent;

        // 查找第一个高亮元素并滚动到它的位置
        const firstHighlight = document.querySelector('.highlight');
        if (firstHighlight) {
            firstHighlight.scrollIntoView({ behavior: 'smooth' });
        }
    }

    // 监听回车键
    document.getElementById('searchBox').addEventListener('keyup', function(event) {
        if (event.key === 'Enter') {
            search();
        }
    });

    // 存储原始内容
    let originalContent;
</script>

</body>
</html>

**Comment by shenweiyan** [comment]
目前没有页内搜索计划，谢谢。
