### ISSUE TITLE
请问如何关闭搜索功能

### ISSUE THREAD

**Issue by itgoyo** [shenweiyan/WebStack-Hugo#48]
简单看了一下配置文件，一下子没找到对应的地方，因为项目的搜索是搜索引擎的搜索，占用了1/3的屏幕高度，所以想问问搜索功能是否可以手动启用

**Comment by shenweiyan** [comment]
在配置文件中目前没有关闭搜索引擎的选项的，如果想关闭搜索功能可以把这一部分的代码直接删除。具体操作如下：

找到 `layouts/index.html`，然后把下面这一行代码**删除掉**即可。
```
{{ partial "content_search.html" . }}
```

**Comment by itgoyo** [comment]
有用！非常感谢
