### ISSUE TITLE
按教程使用vercel部署后，左侧栏的图标都是小框框

### ISSUE THREAD

**Issue by runishiwo** [shenweiyan/WebStack-Hugo#51]
是哪里设置有问题嘛
[navsite-amber.vercel.app](https://navsite-amber.vercel.app/)

**Comment by shenweiyan** [comment]
你的静态资源依旧用的 <https://bioit.top> 的链接，你需要把 `config.toml` 文件中的 `baseURL` 修改成 `baseURL = https://navsite-amber.vercel.app/`。

![Clip_2024-09-03_15-12-26](https://github.com/user-attachments/assets/aa3c13d6-f85d-4e88-88fc-e97c6ccd030d)

**Comment by runishiwo** [comment]
111 感谢

**Comment by runishiwo** [comment]
> 你的静态资源依旧用的 https://bioit.top 的链接，你需要把 文件中的 修改成 。`config.toml``baseURL``baseURL = https://navsite-amber.vercel.app/`
> 
> ![Clip_2024-09-03_15-12-26](https://private-user-images.githubusercontent.com/26101369/363877269-aa3c13d6-f85d-4e88-88fc-e97c6ccd030d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTEwNjUsIm5iZiI6MTcyNTM1MDc2NSwicGF0aCI6Ii8yNjEwMTM2OS8zNjM4NzcyNjktYWEzYzEzZDYtZjg1ZC00ZTg4LTg4ZmMtZTk3YzZjY2QwMzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA4MDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YWQwNDBhMWI5ZjQ0ZmYzZGNlZjQ5NTAzNjE2YTQ2ODRjNTdkOTU1NTk5YTkzMWIzMTc3ZGZmMjJkZWIyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.khLzBO2CWXtHbHJWmTEgIQrwS-mfpGYtH5hMuJ3NqyY)

感谢，已经解决了
