### ISSUE TITLE
Nav-Manage为WebStack-Hugo带来强大的一键管理增强扩展

### ISSUE THREAD

**Issue by rcy1314** [shenweiyan/WebStack-Hugo#52]
[Nav-Manage](https://github.com/rcy1314/nav-manage)是为静态导航而开发的功能增强为主的扩展，它由后端API+前端扩展组成，使用该项目，你可以轻松添加删除你的网站书签、搜索你的书签、更新推送通知到你的社群，更好的获取网站更新内容及带来一些自动化的体验！

开源地址：https://github.com/rcy1314/nav-manage

后端支持一键部署到 Railway和Zeabur，只需要添加环境变量即可，它同样也开源了适合云服务器及本地运行的后端文件，使得在扩展中只需填入服务端运行地址即可，本地及云服务器运行没有api限制

**Comment by rcy1314** [comment]
如果你喜欢该项目，我还在[WebStack-Hugo模版](https://github.com/rcy1314/webstack-hugo-templates)中添加了github-action运行的检测网站失效自动删除的[脚本](https://github.com/rcy1314/webstack-hugo-templates/blob/main/main.py)及[工作流文件](https://github.com/rcy1314/webstack-hugo-templates/blob/main/.github/workflows/link-check.yml)期待WebStack-Hugo可以更好的优化前端体验

**Comment by shenweiyan** [comment]
这个项目厉害了，点个赞！
