### ISSUE TITLE
页面选择子分类

### ISSUE THREAD

**Issue by keli365** [shenweiyan/WebStack-Hugo#54]
![2](https://github.com/user-attachments/assets/9b31b763-99ec-4ac3-b88c-6c37a5e9f0ff)

这种页面带子分类的生成好实现吗

**Comment by shenweiyan** [comment]
我看到好像有人（<https://docs.apachecn.org/>）已经实现了，但是有点 bug，且效果也不太如 WordPress 的版本。具体的我也不清楚是怎么实现的。
