### ISSUE TITLE
请问移动端访问时候菜单不见了，按钮也没有，在哪里配置能出现菜单按钮？

### ISSUE THREAD

**Issue by wangdongyoung** [shenweiyan/WebStack-Hugo#56]
如题。

**Comment by wangdongyoung** [comment]
![微信截图_20241117221641](https://github.com/user-attachments/assets/78bb0934-0083-40fa-9a25-932d8dd0b544)

**Comment by shenweiyan** [comment]
应该是哪里的静态资源出问题了吧，单看描述判断不出来什么问题

**Comment by wangdongyoung** [comment]
以前都没问题啊 我重新下载了最新的文件包 现在换两台电脑 都有这个问题
会是因为我电脑没有f盘的问题么？

**Comment by shenweiyan** [comment]
感谢提醒，这个问题在 [c8182b5](https://github.com/shenweiyan/WebStack-Hugo/commit/c8182b502489b4d6881888c04f8b09b820f5e1e5) 最新版中已经修复了。
