### ISSUE TITLE
无法生成静态文件目录./public

### ISSUE THREAD

**Issue by moxv** [shenweiyan/WebStack-Hugo#6]
我使用hugo命令无法生成静态文件目录，这样我就无法使用静态文件托管，我使用的是0.104.3拓展版本的hugo搭建的，请问是出自的哪里的问题

**Comment by shenweiyan** [comment]
1. 暂时不建议使用拓展版本的 hugo；

2. 默认情况下，生成静态页面输出的内容位于`./docs/`目录中（可以通过`-d/--destination`参数修改输出位置，或者在`config.toml`配置文件中设置`publishDir` 参数）。

**Comment by moxv** [comment]
> 1. 暂时不建议使用拓展版本的hugo；
> 2. 下情况，生成输出页面输出的内容在`./docs/`中（可以通过`-d/--destination`修改参数位置，或者在默认`config.toml`配置文件目录中设置`publishDir`参数）。

顶部图片如何自适应，宽屏的话图片就自动填充为两张了

**Comment by shenweiyan** [comment]
> 顶部图片如何自适应，宽屏的话图片就自动填充为两张了

这个暂时没法自适应，或者可以设置一个纯色的图片
