### ISSUE TITLE
请问底下的background哪里修改？

### ISSUE THREAD

**Issue by zyancn** [shenweiyan/WebStack-Hugo#7]
我部署在vercel上的，请问这个底下这个background在哪里调整？没找到对应的代码，赶紧方格看的眼镜花了。。。。还有网站内的侧边栏icon是哪个资源库的，也没有找到对应的地方，被迫挂了bootstrap的图标库，不知道会不会冲突。

**Comment by shenweiyan** [comment]
> 我部署在vercel上的，请问这个底下这个background在哪里调整？没找到对应的代码，赶紧方格看的眼镜花了。。。。还有网站内的侧边栏icon是哪个资源库的，也没有找到对应的地方，被迫挂了bootstrap的图标库，不知道会不会冲突。

1. 网格 background 的代码参考以下两个文件：
   - layouts/partials/content_header.html
   - static/assets/css/custom-style.css
![image](https://user-images.githubusercontent.com/26101369/210042594-714de3d3-f6c5-4fd6-ad02-65b9aa46194e.png)

2. 侧边栏 icon 用的 [Font Awesome](https://fontawesome.com/) 的图标。

**Comment by zyancn** [comment]
搞定，谢谢！
