### ISSUE TITLE
[BUG] 左侧侧边栏菜单显示不全

### ISSUE THREAD

**Issue by AndaBrown** [shenweiyan/WebStack-Hugo#8]
![image](https://user-images.githubusercontent.com/103917160/212462436-04e815d7-958d-49df-8257-a549e527d955.png)
![image](https://user-images.githubusercontent.com/103917160/212462483-0ecc3e2e-30f4-4a84-8db4-4b8f5dfbaf04.png)
菜单展开后会有一部分被遮挡，好像菜单并不支持滚动。
图1：最后一个主菜单展开后下面的分项目显示不全
图2：展开其他主菜单后会遮挡下面的主菜单
缩小浏览器窗口高度后遮挡更严重。
希望菜单支持一下滚动。

**Comment by shenweiyan** [comment]
感谢，我去看一下

**Comment by shenweiyan** [comment]
左侧导航菜单现在已经支持滚动了 >.<
