### ISSUE TITLE
请教：如何将头部链接设置为新窗口打开

### ISSUE THREAD

**Issue by zmtter** [shenweiyan/WebStack-Hugo#9]
想请教：如何将头部链接设置为新窗口打开，而非当前窗口打开。即下图红框中的链接，非常感谢
![image](https://user-images.githubusercontent.com/87307698/218238143-6b7df10d-5781-4640-9cc1-11a034ab328a.png)

**Comment by shenweiyan** [comment]
> 想请教：如何将头部链接设置为新窗口打开，而非当前窗口打开。即下图红框中的链接，非常感谢 ![image](https://user-images.githubusercontent.com/87307698/218238143-6b7df10d-5781-4640-9cc1-11a034ab328a.png)

可以修改 `layouts/partials/content_header.html` 文件中下面这部分代码：
```
<ul class="navbar-nav site-menu" style="margin-right: 16px;">
    {{ range .Site.Data.headers }}
    <li {{ if .list }}class="menu-item-has-children"{{ end }}>
        <a href="{{ .link }}">
            <i class="{{ .icon }} fa-lg mr-2"></i>
            <span>{{ .item }}</span>
        </a>
        <ul class="sub-menu">
        {{ range .list }}
            <li><a href="{{ .url }}">{{ .name }}</a></li>
        {{ end }}
        </ul>
    </li>
    {{ end }}
</ul>
```
把里面全部的 `<a>` 标签都增加一个 `target="_blank"` 的属性就可以了，如：
```
<a href="......">
```
变成：
```
<a href="....." target="_blank">
```
